name: Code Quality

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: nt-postman

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test

    # Run test scripts
    - name: Check codeing standards
      run: test/test_phpcs.sh

    - name: Check syntax
      run: test/test_for_syntax_errors.sh

    - name: Package plugin
      run: |
        mkdir ${{ env.PACKAGE_NAME }} |
        cp -r nt-postman.php LICENSE tile site-link magic-link documentation version-control.json ${{ env.PACKAGE_NAME }}/

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ env.PACKAGE_NAME }}
