name: Code Quality

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: nt-postman
      DB_NAME: testdb
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PW }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Check codeing standards
      run: test/test_phpcs.sh

    - name: Check syntax
      run: test/test_for_syntax_errors.sh

    - name: Package plugin
      run: |
        mkdir ${{ env.PACKAGE_NAME }}
        cp -r nt-postman.php LICENSE tile site-link magic-link documentation version-control.json ${{ env.PACKAGE_NAME }}/
        zip -r ${{ env.PACKAGE_NAME }}.zip ${{ env.PACKAGE_NAME }}

    - name: Test plugin installation
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        test/test_installation.sh

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ env.PACKAGE_NAME }}
