name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_NAME: nt-postman
    steps:
      - uses: actions/checkout@v2

      - name: Package plugin
        run: .github/scripts/package_plugin.sh

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.PACKAGE_NAME }}.zip
          bodyFile: "CHANGELOG.md"
          token: ${{ secrets.GITHUB_TOKEN }}
